name: Psych60_Python368

dependencies:
 - python=3.6.8
 - autopep8
 - cloudpickle==0.8.0
 - ipython
 - ipykernel
 - ipywidgets
 - jupyter
 - jupyterlab
 - mkl-service
 - nb_conda_kernels
 - matplotlib>=3.0.3
 - networkx
 - numpy>=1.16.2
 - pandas>=0.24.2
 - pywavelets
 - statsmodels>=0.9.0
 - scikit-image
 - scikit-learn>=0.20.3
 - scipy>=1.2.1
 - seaborn
 - sympy>=1.3
 - pip
 - pip:
    - duecredit
    - fmriprep>=1.3.2
    - hypertools>=0.5.1
    - mne>=0.17.2
    - nilearn>=0.5.2
    - nibabel>=2.4.0
    - nipype>=1.1.9
    - nltools>=0.3.13
    - mriqc>=0.15.0
    - pynv>=0.1.1
    - pytest>=4.3.1
    - pybids>=0.8.0
    - six>=1.12.0
